### PR TITLE
Added send test email option

### PR DESCRIPTION
**Pull request by Schmidie64**
Pull Request for Issue #22126 .

### Summary of Changes

Added a send test-mail button for @Hackwar PR. 
This option allows you to send a test-email with a specific mail-template chosen to every valid email-address.

### Testing Instructions
Send_Test_Mail_Button
1. Go to your Joomla adminsite
2. Change your url to http://{sitename}**/index.php?option=com_mails&amp;view=templates**
3. In the left upper corner you can find the "Send Test E-Mail Button"
4. Now a modal windows will be open
5. Now you can enter the email-address where the email will be send to
6. Choose a template for the test mail
7. Press the "send test e-mail button"
8. Now you should received a email with the chosen template

### CODE REVIEW

**Comment by Hackwar** [comment]
How does that fill the data for the template?

**Comment by Schmidie64** [comment]
Currently it use hard coded values. This ist an Open question how to Deal with the dynamic value. Maybee @wilsonge can answer These question.

**Comment by wilsonge** [comment]
I honestly have no clue how to deal with template data :) You can do plugin events I guess but it kinda sucks because for components sending emails you then mandate plugins per component to send test emails. I also considered in the mail template table storing the extension and going through the bootComponent

**Comment by Schmidie64** [comment]
What do you think @Hackwar?

**Comment by Schmidie64** [comment]
For now i implemented a replacement for the placeholders in the test-email. You can change the placeholder-value via an language override. If there is a final decision on how to deal with this feature, then we can consult again about this function. 

@roland-d

**Pull request closed without merging**
