### PR TITLE
JRouter performance improvements and legacy component fix

### PR DESCRIPTION
**Pull request by mahagr**
I have always hated how slow Joomla router really is. This pull request improves JRoute::_() performance by factor of 4 (5 if you compare with Joomla/master). The changes are really small -- we just cache few objects instead of fetching them every time.

I have also fixed a bug where existing KunenaRouter class was mistaken to the new class.

This pull request also contains commits from Joomla/master.

Enjoy!

### CODE REVIEW

**Comment by mahagr** [comment]
In practice the improvements have really huge impact on the site performance if there are a lot of links in the page.

Here's an example from Kunena Index page with 100 categories and ~300 links in my test environment:
master branch: Time to create page: 0.423 seconds
jrouter branch: Time to create page: 0.298 seconds

Note that Kunena is unmodified and still using the old router functions.

That means -0.12 seconds or 40% improvement in the component performance. Also Apache benchmark shows 25% improvement between the otherwise identical sites.

**Comment by Hackwar** [comment]
Hi mahagr,
thanks for this pull request, on a first glance it looks really good. I will have a deeper look this evening. Most of your changes look like a sensible way to go.

One thing: The menu object that you are storing in the static var, is that a reference to the object returned by JApplication or is that a copy? The background is, that at some point in the future I'd like to make it possible that a component can add items on the fly to the menu system and if JRouter creates a copy of the menu object before the component has been executed, the changes from the component would not have any effect in JRouter.

**Comment by mahagr** [comment]
Objects are always passed as reference in PHP5, so there's no need to use references unless you're using arrays or strings. To copy the object, you need to clone it.

So data is always up to date, especially as Joomla doesn't allow replacing those objects after the first getInstance(). The performance boost comes from the fact that calling JFactory method that calls JRoute/JMenu method costs small amount of time that got multiplied 5*JRoute::_() calls. In my example there was ~1500 extra calls (instead of 3) -- so using only 0.0008 seconds in one call cumulates and end up making a huge difference.

Please look my 2 commits only as everything else is already in the Joomla/master branch (I just pulled your changes into my branch).

**Comment by mahagr** [comment]
BTW: I would like to try to improve your new router so, that it would work with Kunena. Kunena 2.0 has perhaps the most advanced routing in Joomla. It automatically picks up the best possible Itemid and it's optimized for speed.

There are some tasks that should be left for the component to decide (picking Itemid etc). There are also a few things that seem to be hard to do with the new plugin.

**Comment by Hackwar** [comment]
Could you contact me via skype or on IRC so that we can chat directly about your plans?

Skype: hackwar1983
IRC: Hackwar on freenode (I normally idle in #joomla)

The new router is not performance optimized and there are some things that maybe should be done a little bit differently. Other things I feel quite strongly about. ;-) So maybe we can work on this together.

In general, the idea is, that only the display task gets SEF URLs via the rules provided by the joomla router plugin. So only URLs containing &view= get SEFed. Everything else should only be called and then redirect to a task=display URL again.

**Comment by Hackwar** [comment]
In general, the JComponentRouter class is for the lazy developers. If you don't want to, you don't have to extend from that class. The only thing that you have to provide is the parse() and build() method in your implementation.

**Comment by Hackwar** [comment]
After a nice chat, we found a few more improvements. Accepting the request now. ;-)

**Pull request merged**
